name: Upgrade to Bot Account (ONE TIME ONLY)

on:
  workflow_dispatch:   # manual trigger only

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upgrade account to BOT
        run: |
          chmod +x ./scan_linux
          python3 lidraughts-bot.py -u
        env:
          LIDRAUGHTS_BOT_TOKEN: ${{ secrets.LIDRAUGHTS_BOT_TOKEN }}
